import type { NextPage } from 'next';
import Head from 'next/head';

import {
  PageContent, PageContainer, PageTitle, PageParagraph,
} from '../styles/css';

const Services: NextPage = () => (
  <PageContainer style={{ margin: '32px 0' }}>
    <Head>
      <title>Not Found - - DoDesign</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <PageContent>
      <PageTitle>404</PageTitle>
      <PageParagraph style={{ margin: '48px 0 0 0', textAlign: 'center' }}>Page not found</PageParagraph>
    </PageContent>
  </PageContainer>
);

export default Services;
