import type { NextPage } from 'next';
import Head from 'next/head';

const About: NextPage = () => (
    <div>
      <Head>
        <title>Home - DoDesign</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      About
    </div>
);

export default About;
