import type { NextPage } from 'next';
import Head from 'next/head';

import {
  PageContent, PageContainer, PageTitle, PageParagraph,
} from '../styles/css';

const About: NextPage = () => (
  <PageContainer>
    <Head>
      <title>About - - DoDesign</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <PageContent>
      <PageTitle>About</PageTitle>
      <PageParagraph style={{ margin: '48px 0 0 0' }}>
        Do.Design is a reflection of conciseness, individual style and high service. We think that life is easy,
        comfortable and beautiful - this is the norm, you just need to want it. Then contact us and let us do the rest.
        We will do everything to ensure that our client is comfortable at all stages of collaboration, and the interior
        pleases for many years. And most importantly - was truly &apos;yours&apos;.
      </PageParagraph>
      <PageParagraph style={{ margin: '48px 0 0 0', maxWidth: '70%' }}>
        Benefits of working with us:
        {'\n\n'}- We try for you
        {'\n\n'}- Unique style
        {'\n'}
        We are moving away from stereotyped techniques and for each client we develop a personal design project with
        real materials and objects in our style.
        {'\n\n'}- Full cycle of works
        {'\n'}
        We take care of all the difficulties in the implementation of the project - from the coordination of
        redevelopment to the purchase of furniture.
        {'\n\n'}- Team of professionals
        {'\n'}
        We bring projects to life exactly as pictured with our own construction teams who have proven their skills in
        practice.
        {'\n\n'}- The main areas of our work are:
        {'\n'}Interior Design;
        {'\n'}Exterior design;
        {'\n'}Subject design.
        {'\n\n'}For all questions, please contact us by contact numbers or e-mail. The studio is open seven days a week.
      </PageParagraph>
    </PageContent>
  </PageContainer>
);

export default About;
