import type { NextPage } from 'next';
import Head from 'next/head';

import { PageContent, PageContainer, PageTitle } from '../styles/css';

const Contact: NextPage = () => (
    <PageContainer>
      <Head>
        <title>Contact- DoDesign</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContent>
        <PageTitle>Contact</PageTitle>
      </PageContent>
    </PageContainer>
);

export default Contact;
