import type { NextPage } from 'next';
import Head from 'next/head';

import { PageContent, PageContainer, PageTitle } from '../styles/css';

const Projects: NextPage = () => (
    <PageContainer>
      <Head>
        <title>Projects - - DoDesign</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContent>
        <PageTitle>Projects</PageTitle>
      </PageContent>
    </PageContainer>
);

export default Projects;
